In [ ]:
#downloading dataset

!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

--2023-05-04 15:56:23--  https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: ‘input.txt’

input.txt           100%[===================>]   1.06M  --.-KB/s    in 0.008s  

2023-05-04 15:56:23 (139 MB/s) - ‘input.txt’ saved [1115394/1115394]



In [ ]:
#opening the file and reading it

with open('input.txt', 'r', encoding = 'utf-8') as f:
  text = f.read()

In [ ]:
text[:1000]

"First Citizen:\nBefore we proceed any further, hear me speak.\n\nAll:\nSpeak, speak.\n\nFirst Citizen:\nYou are all resolved rather to die than to famish?\n\nAll:\nResolved. resolved.\n\nFirst Citizen:\nFirst, you know Caius Marcius is chief enemy to the people.\n\nAll:\nWe know't, we know't.\n\nFirst Citizen:\nLet us kill him, and we'll have corn at our own price.\nIs't a verdict?\n\nAll:\nNo more talking on't; let it be done: away, away!\n\nSecond Citizen:\nOne word, good citizens.\n\nFirst Citizen:\nWe are accounted poor citizens, the patricians good.\nWhat authority surfeits on would relieve us: if they\nwould yield us but the superfluity, while it were\nwholesome, we might guess they relieved us humanely;\nbut they think we are too dear: the leanness that\nafflicts us, the object of our misery, is as an\ninventory to particularise their abundance; our\nsufferance is a gain to them Let us revenge this with\nour pikes, ere we become rakes: for the gods know I\nspeak this in hunger 

In [ ]:
print(text[:1000])  #first 1000 characters

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.



In [ ]:
print(len(text))

1115394


In [ ]:
print(set(text))

{'F', 'A', 'o', 'C', 'x', '$', 'M', 'g', 'U', '3', 'R', 'Z', 'c', 'I', 'E', 'm', 't', 'k', 'b', 'p', 'h', 'l', 'n', 'y', 'N', 'q', ' ', 'w', ';', 'H', '-', 'O', '!', 'a', 'B', 'T', 'G', '\n', 'P', 'z', "'", '&', 'f', 'Q', ',', 'V', ':', 'J', 'd', 'j', 'K', '.', 's', 'L', 'u', 'S', 'W', 'e', 'i', 'r', '?', 'X', 'D', 'v', 'Y'}


In [ ]:
print(sorted(set(text)))

['\n', ' ', '!', '$', '&', "'", ',', '-', '.', '3', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


In [ ]:
char_list  = list(sorted(set(text)))

In [ ]:
print(char_list)

['\n', ' ', '!', '$', '&', "'", ',', '-', '.', '3', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


In [ ]:
print(''.join(char_list))


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz


In [ ]:
vocab_size = len(char_list)

In [ ]:
vocab_size

65

# Encoding text:

In [ ]:
#character level tokenizer

stoi = {}

for char, i in enumerate(char_list):
  stoi[i] = char

In [ ]:
print(stoi)

{'\n': 0, ' ': 1, '!': 2, '$': 3, '&': 4, "'": 5, ',': 6, '-': 7, '.': 8, '3': 9, ':': 10, ';': 11, '?': 12, 'A': 13, 'B': 14, 'C': 15, 'D': 16, 'E': 17, 'F': 18, 'G': 19, 'H': 20, 'I': 21, 'J': 22, 'K': 23, 'L': 24, 'M': 25, 'N': 26, 'O': 27, 'P': 28, 'Q': 29, 'R': 30, 'S': 31, 'T': 32, 'U': 33, 'V': 34, 'W': 35, 'X': 36, 'Y': 37, 'Z': 38, 'a': 39, 'b': 40, 'c': 41, 'd': 42, 'e': 43, 'f': 44, 'g': 45, 'h': 46, 'i': 47, 'j': 48, 'k': 49, 'l': 50, 'm': 51, 'n': 52, 'o': 53, 'p': 54, 'q': 55, 'r': 56, 's': 57, 't': 58, 'u': 59, 'v': 60, 'w': 61, 'x': 62, 'y': 63, 'z': 64}


In [ ]:
import torch

def encode(text, stoi):
  encode = []
  for char in text:
    encode.append(stoi[char])
  return torch.tensor(encode, dtype = torch.long)

In [ ]:
def decode(encode, stoi):
  decode= []
  for enc in encode:
    decode.append(list(stoi.keys())[enc])
  return (''.join(decode))

In [ ]:
text = "hii there"
encode_text = encode(text, stoi)
decode_text = (decode(encode(text, stoi), stoi))

In [ ]:
print(encode_text)
print(decode_text)

tensor([46, 47, 47,  1, 58, 46, 43, 56, 43])
hii there


Other tokeninzing techniques: 


1) Google uses: sentencepiece (github) text->int, sub-word tokenizer.

2) tiktoken: Open ai uses it for chat gpt.

In [ ]:
!pip install tiktoken

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 67.0 MB/s eta 0:00:00


In [ ]:
import tiktoken

enc = tiktoken.get_encoding('gpt2')
print(f" vocab length: {enc.n_vocab}")

 vocab length: 50257


In [ ]:
enc.encode("hii there")

[71, 4178, 612]

In [ ]:
enc.decode(enc.encode("hii there"))

'hii there'

# Tokeninzing the entire training set:

In [ ]:
import torch

text = 'hii there'
encode_text = torch.tensor(encode(text, stoi), dtype= torch.long)
print(f"{encode_text, type(encode_text)}")

(tensor([46, 47, 47,  1, 58, 46, 43, 56, 43]), <class 'torch.Tensor'>)


<ipython-input-24-3202024718c8>:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  encode_text = torch.tensor(encode(text, stoi), dtype= torch.long)


In [ ]:
##encoding some part of dataset
with open('input.txt', 'r', encoding = 'utf-8') as f:
  text = f.read()

In [ ]:
encode(text[:1000], stoi)

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1, 39, 56, 43,  1, 39, 50, 50,
         1, 56, 43, 57, 53, 50, 60, 43, 42,  1, 56, 39, 58, 46, 43, 56,  1, 58,
        53,  1, 42, 47, 43,  1, 58, 46, 39, 52,  1, 58, 53,  1, 44, 39, 51, 47,
        57, 46, 12,  0,  0, 13, 50, 50, 10,  0, 30, 43, 57, 53, 50, 60, 43, 42,
         8,  1, 56, 43, 57, 53, 50, 60, 43, 42,  8,  0,  0, 18, 47, 56, 57, 58,
         1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 18, 47, 56, 57, 58,  6,  1, 63,
        53, 59,  1, 49, 52, 53, 61,  1, 15, 39, 47, 59, 57,  1, 25, 39, 56, 41,
        47, 59, 57,  1, 47, 57,  1, 41, 

In [ ]:
print(decode(encode(text[:1000], stoi), stoi))

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.



In [ ]:
print(decode(encode(text[:1000], stoi), stoi) == text[:1000])

True


In [ ]:
data = encode(text, stoi)

In [ ]:
print(len(text))

1115394


In [ ]:
print(data.shape, data.dtype)

torch.Size([1115394]) torch.int64


In [ ]:
#train test split

train_data = data[:int(0.9*len(data))]   #90% of the data 
val_data = data[int(0.9*len(data)):]    #rest 10% of data

In [ ]:
print(train_data.shape, val_data.shape)

torch.Size([1003854]) torch.Size([111540])


In [ ]:
#transformers are based on chuks of dataset, chuncks- block size

block_size = 8
train_data[:block_size+1]

# 8 individual examples, in context of 18, 47 comes next
# in context of 18,47 , 56 comes next

# in context of 18,47,56   , 57 comes next

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

In [ ]:
#time dimension

X =  train_data[:block_size+1]
for i in range(len(train_data[:block_size+1])-1):
  print(f"in context of {X[:i+1]} the target is {X[i+1]}")

in context of tensor([18]) the target is 47
in context of tensor([18, 47]) the target is 56
in context of tensor([18, 47, 56]) the target is 57
in context of tensor([18, 47, 56, 57]) the target is 58
in context of tensor([18, 47, 56, 57, 58]) the target is 1
in context of tensor([18, 47, 56, 57, 58,  1]) the target is 15
in context of tensor([18, 47, 56, 57, 58,  1, 15]) the target is 47
in context of tensor([18, 47, 56, 57, 58,  1, 15, 47]) the target is 58


In [ ]:
ix = torch.randint(len(train_data) - 8, (4,))

In [ ]:
ix

tensor([722544, 978233, 781311, 386257])

In [ ]:
# input
torch.stack([train_data[i:i+8] for i in ix])

tensor([[49, 43, 52,  0, 14, 63,  1, 39],
        [10,  0, 25, 39, 56, 56, 63,  6],
        [59,  6,  1, 57, 47, 56,  6,  1],
        [41, 43,  1, 44, 43, 39, 56,  1]])

In [ ]:
#target
torch.stack([train_data[i+1:i+8+1] for i in ix])

tensor([[43, 52,  0, 14, 63,  1, 39, 52],
        [ 0, 25, 39, 56, 56, 63,  6,  1],
        [ 6,  1, 57, 47, 56,  6,  1, 21],
        [43,  1, 44, 43, 39, 56,  1, 53]])

In [ ]:
# multiple chunks at the same time

torch.manual_seed(1337)
batch_size = 4 # how many independent sequence will be processed parallel to minize gpu load
block_size = 8 # individual sequence lengths


def get_batch(split):

  data = train_data if split == 'train' else val_data
  rand_vals = torch.randint(len(data) - block_size, (batch_size,))
  x = torch.stack([data[i:i+block_size] for i in rand_vals])
  y = torch.stack([data[i+1: i+block_size+1] for i in rand_vals])
  return x,y

X,y = get_batch('train')
print(f'inputs: {X.shape} \n {X}')
print(f'targets: {y.shape} \n {y}')



inputs: torch.Size([4, 8]) 
 tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])
targets: torch.Size([4, 8]) 
 tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])


In [ ]:
for b in range(batch_size): #batch_dimension
  for t in range(block_size):  #time_dimension
    context = X[b, :t+1]
    target = y[b,t]
    print(f'when input is {context} output is {target}')

when input is tensor([24]) output is 43
when input is tensor([24, 43]) output is 58
when input is tensor([24, 43, 58]) output is 5
when input is tensor([24, 43, 58,  5]) output is 57
when input is tensor([24, 43, 58,  5, 57]) output is 1
when input is tensor([24, 43, 58,  5, 57,  1]) output is 46
when input is tensor([24, 43, 58,  5, 57,  1, 46]) output is 43
when input is tensor([24, 43, 58,  5, 57,  1, 46, 43]) output is 39
when input is tensor([44]) output is 53
when input is tensor([44, 53]) output is 56
when input is tensor([44, 53, 56]) output is 1
when input is tensor([44, 53, 56,  1]) output is 58
when input is tensor([44, 53, 56,  1, 58]) output is 46
when input is tensor([44, 53, 56,  1, 58, 46]) output is 39
when input is tensor([44, 53, 56,  1, 58, 46, 39]) output is 58
when input is tensor([44, 53, 56,  1, 58, 46, 39, 58]) output is 1
when input is tensor([52]) output is 58
when input is tensor([52, 58]) output is 1
when input is tensor([52, 58,  1]) output is 58
when inpu

In [ ]:
print(X)

tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])


In [ ]:
## bigram language model

import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):   #bigramlangmodel is subclass of nn module

  def __init__(self, vocab_size):
    super().__init__()
    self.token_embeding_table = nn.Embedding(vocab_size, vocab_size)    #(65,65)

    #so when idx is given as an input eavery interger in it ex: 24 will pluck out 24th row and 43 will pluck out 43 rd row

  def forward(self, idx, target):

    #idx and target are both (batch_size 'B', block_size or timen_dimension 'T') tensor of integers

    logits = self.token_embeding_table(idx)  # pytorch arranges the row which were plucked out in : (B,T,C) format   
    
    #input idx 'X' is passed on to the token_embedding_table

    return logits # scores of what comes next as we are generating things, predicting based on single current digit 

In [ ]:
m = BigramLanguageModel(vocab_size)
out = m(X,y)
print(out.shape)

torch.Size([4, 8, 65])


In [ ]:
## adding loss function to it

## bigram language model

import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):   #bigramlangmodel is subclass of nn module

  def __init__(self, vocab_size):
    super().__init__()
    self.token_embeding_table = nn.Embedding(vocab_size, vocab_size)    #(65,65)

    #so when idx is given as an input eavery interger in it ex: 24 will pluck out 24th row and 43 will pluck out 43 rd row

  def forward(self, idx, target = None):

    #idx and target are both (batch_size 'B', block_size or timen_dimension 'T', channels 'C' or vocab size) tensor of integers

    logits = self.token_embeding_table(idx)  # pytorch arranges the row which were plucked out in : (B,T,C) format   
    
    #input idx 'X' is passed on to the token_embedding_table

    ####loss function - negative log likelihood loss

    ##cross entropy expects input in (B,C,T) format

    B,T,C = logits.shape

    logits = logits.view(B*T, C)   #changing dimension for loss
    target = target.view(B*T) 
    loss = F.cross_entropy(logits, target)

    return logits, loss # scores of what comes next as we are generating things, predicting based on single current digit


In [ ]:
m = BigramLanguageModel(vocab_size)
out, loss = m(X,y)
print(out.shape, loss)

torch.Size([32, 65]) tensor(4.8786, grad_fn=<NllLossBackward0>)


In [ ]:
## adding generate function

## adding loss function to it

## bigram language model

import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):   #bigramlangmodel is subclass of nn module

  def __init__(self, vocab_size):
    super().__init__()
    self.token_embeding_table = nn.Embedding(vocab_size, vocab_size)    #(65,65)

    #so when idx is given as an input eavery interger in it ex: 24 will pluck out 24th row and 43 will pluck out 43 rd row

  def forward(self, idx, target = None):

    #idx and target are both (batch_size 'B', block_size or timen_dimension 'T', channels 'C' or vocab size) tensor of integers

    logits = self.token_embeding_table(idx)  # pytorch arranges the row which were plucked out in : (B,T,C) format   
    
    #input idx 'X' is passed on to the token_embedding_table

    ####loss function - negative log likelihood loss

    ##cross entropy expects input in (B,C,T) format

    if target is None:
      loss = None
    
    else:
      B,T,C = logits.shape

      logits = logits.view(B*T, C)   #changing dimension for loss
      target = target.view(B*T) 
      loss = F.cross_entropy(logits, target)

    return logits, loss # scores of what comes next as we are generating things, predicting based on single current digit


  def generate(self, idx, max_new_tokens):   ##here the word history is not used just the last word is check to predict the next word but everything is beinf fed to the model
    for _ in range(max_new_tokens):

      logits, loss = self(idx)  #calling the forward function
      logits = logits[:, -1, :]   #logits now become (B,C), pluck out the last element from the time dimension
      #applying softmax to get the probabilities

      probs = F.softmax(logits, dim = 1) #(b,c)
      #sample from the distribution

      idx_next = torch.multinomial(probs, num_samples = 1)
      #append sampled index to the running sequence
      idx = torch.cat((idx, idx_next), dim = 1)  #(b,t+1)

    return idx


In [ ]:
m = BigramLanguageModel(vocab_size)
out, loss = m(X,y)
print(out.shape, loss)

torch.Size([32, 65]) tensor(4.8786, grad_fn=<NllLossBackward0>)


In [ ]:
idx = torch.zeros((1,1), dtype = torch.long)
print(decode(m.generate(idx, max_new_tokens = 100).tolist()[0],stoi))


Sr?qP-QWktXoL&jLDJgOLVz'RIoDqHdhsV&vLLxatjscMpwLERSPyao.qfzs$Ys$zF-w,;eEkzxjgCKFChs!iWW.ObzDnxA Ms$3


In [ ]:
#create pytorch optimizer

optimizer = torch.optim.Adam(m.parameters(), lr = 1e-3)

In [ ]:
from tqdm import tqdm

In [ ]:
batch_size = 32

for steps in tqdm(range(10000)):
  #sampling a batch
  X,y = get_batch('train')

  #evaluate the loss
  logits, loss = m(X,y)
  optimizer.zero_grad(set_to_none = True)
  loss.backward()
  optimizer.step()

print(loss.item())

100%|██████████| 10000/10000 [00:10<00:00, 929.58it/s]

2.572469472885132


In [ ]:
print(decode(m.generate(idx, max_new_tokens = 500).tolist()[0],stoi))


Iyoteng h hasbe pave pirance
Rie hicomyonthar's
Plinseard ith henoure wounonthioneir thondy, y heltieiengerofo'dsssit ey
KIN d pe wither vouprrouthercckehathe; d!
My hind tt hinig t ouchos tes; st yo hind wotte grotonear 'so it t jod weancotha:
h hay.JUCle n prids, r loncave w hollular s O:
HIs; ht anjx?

DUThineent.

Lavinde.
athave l.
KEONGBUCHandspo be y,-hedarwnoddy scace, tridesar, wne'shenous s ls, theresseys
PlorseelapinghiybHen yof GLUCEN t l-t E:
I hisgothers w dere! ABer wotouciullle's


##Mathematical trick for self attention

In [ ]:
B, T, C = 4, 8, 2

x = torch.randn(B, T, C)
x.shape

torch.Size([4, 8, 2])

Coupling tokens: token at 5th location should communicate with 5th, 4th 3rd 2nd and 1st token, this can be done by averaging of the previous tokens.

In [ ]:
xbow = torch.zeros((B, T, C))

In [ ]:
for b in range(B):
  for t in range(T):
    xprev = x[b, :t+1]  #all prev instances for a particular(b,t)
    xbow[b,t] = torch.mean(xprev, dim=0)

In [ ]:
x[0]

tensor([[-6.6515e-01,  7.6920e-01],
        [-1.0856e+00, -7.4231e-01],
        [-1.1869e+00, -1.4491e+00],
        [-8.9321e-01, -7.0390e-01],
        [ 1.6554e-01, -1.5425e+00],
        [-3.4596e-01, -9.2675e-02],
        [ 7.0194e-01, -9.7682e-04],
        [ 1.3636e-01,  6.1380e-01]])

In [ ]:
xbow[0]

tensor([[-0.6651,  0.7692],
        [-0.8754,  0.0134],
        [-0.9792, -0.4741],
        [-0.9577, -0.5315],
        [-0.7331, -0.7337],
        [-0.6686, -0.6269],
        [-0.4728, -0.5375],
        [-0.3966, -0.3936]])

In [ ]:
(x[0,0] + x[0,1])/2

tensor([-0.8754,  0.0134])

In [ ]:
xbow[0,1]

tensor([-0.8754,  0.0134])

In [ ]:
(x[0,0] + x[0,1] + x[0,2])/3

tensor([-0.9792, -0.4741])

In [ ]:
xbow[0,2]

tensor([-0.9792, -0.4741])

In [ ]:
#mathematical trick

torch.manual_seed(42)
a = torch.ones(3,3)
b = torch.randint(0, 10, (3,2)).float()
c = a @ b 

print(a, a.shape)
print(b, b.shape)
print(c, c.shape)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) torch.Size([3, 3])
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]]) torch.Size([3, 2])
tensor([[14., 16.],
        [14., 16.],
        [14., 16.]]) torch.Size([3, 2])


In [ ]:
#lower tirangular matrix

torch.tril(torch.ones(3,3))

tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])

In [ ]:
#trick!!
#here we are summing

torch.manual_seed(42)
a = torch.tril(torch.ones(3,3))
b = torch.randint(0, 10, (3,2)).float()
c = a @ b 

print(a, a.shape)
print(b, b.shape)
print(c, c.shape)

tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]]) torch.Size([3, 3])
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]]) torch.Size([3, 2])
tensor([[ 2.,  7.],
        [ 8., 11.],
        [14., 16.]]) torch.Size([3, 2])


In [ ]:
#averaging
#every row in a now sum upto 1 with maintaining the ower triangularity
torch.manual_seed(42)
a = torch.tril(torch.ones(3,3))
a = a/torch.sum(a, dim = 1, keepdim = True)
b = torch.randint(0, 10, (3,2)).float()
c = a @ b 

print(a, a.shape)
print(b, b.shape)
print(c, c.shape)

tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]]) torch.Size([3, 3])
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]]) torch.Size([3, 2])
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]]) torch.Size([3, 2])


In [ ]:
(b[0]+b[1]+b[2])/3

tensor([4.6667, 5.3333])

In [ ]:
c[2]

tensor([4.6667, 5.3333])

In [ ]:
wei = torch.tril(torch.ones(T,T))
wei = wei/wei.sum(1, keepdim = True)

In [ ]:
wei

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])

In [ ]:
xbow2 = wei @ x  # (b,t,t) @ (b,t,c) --> (b,t,c)
torch.allclose(xbow, xbow2)

True

In [ ]:
xbow2[0]

tensor([[-0.6651,  0.7692],
        [-0.8754,  0.0134],
        [-0.9792, -0.4741],
        [-0.9577, -0.5315],
        [-0.7331, -0.7337],
        [-0.6686, -0.6269],
        [-0.4728, -0.5375],
        [-0.3966, -0.3936]])

In [ ]:
xbow[0]

tensor([[-0.6651,  0.7692],
        [-0.8754,  0.0134],
        [-0.9792, -0.4741],
        [-0.9577, -0.5315],
        [-0.7331, -0.7337],
        [-0.6686, -0.6269],
        [-0.4728, -0.5375],
        [-0.3966, -0.3936]])

In [ ]:
#method 3

tril = torch.tril(torch.ones(T,T))

In [ ]:
tril

tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
wei = torch.zeros((T,T))

In [ ]:
wei

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
#mask filling wei by -inf where tril is 0
wei = wei.masked_fill(tril == 0, float('-inf'))    

In [ ]:
wei

tensor([[0., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., 0., -inf, -inf, -inf],
        [0., 0., 0., 0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
#applying softmax to wei
wei = F.softmax(wei, dim = 1)


In [ ]:
wei  #exact same matris as before

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])

In [ ]:
xbow3 = wei@x

In [ ]:
xbow3[0]

tensor([[-0.6651,  0.7692],
        [-0.8754,  0.0134],
        [-0.9792, -0.4741],
        [-0.9577, -0.5315],
        [-0.7331, -0.7337],
        [-0.6686, -0.6269],
        [-0.4728, -0.5375],
        [-0.3966, -0.3936]])

In [ ]:
xbow[0]

tensor([[-0.6651,  0.7692],
        [-0.8754,  0.0134],
        [-0.9792, -0.4741],
        [-0.9577, -0.5315],
        [-0.7331, -0.7337],
        [-0.6686, -0.6269],
        [-0.4728, -0.5375],
        [-0.3966, -0.3936]])

In [ ]:
#single attention head

torch.manual_seed(1337)
B,T,C = 4,8,32

x = torch.randn(B,T,C)

head_size = 16
key = nn.Linear(C, head_size, bias = False)
query = nn.Linear(C, head_size, bias = False)
value = nn.Linear(C, head_size, bias = False)
k = key(x)  #(b,t,16)
q = query(x) #(b, t,16)
wei = q @ k.transpose(-2,-1) #(b,t,16) @(b,16,t) --->(b, t, t) 

tril = torch.tril(torch.ones(T,T))
wei = wei.masked_fill(tril ==0, float('-inf'))
wei = F.softmax(wei, dim = -1)

v = value(x)
out = wei @ v
#out = wei @ x

out.shape

#how much information to aggregate from each tokens past


torch.Size([4, 8, 16])

In [ ]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)